### ISSUE TITLE
typescript error?

### ISSUE THREAD

**Issue by jmagaram** [svenwiegand/typed-redux-actions#1]
I'm reading through your example ReadMe, with before and after, and it looks pretty nice. But a small bit of magic doesn't work for me. With just the code below, TypeScript says Cannot find name 'SetAction' which is what I'd expect. How do you get away with not explicitly defining an interface for 'SetAction'? In the ReadMe the tokens for 'IncrementAction' and 'SetAction' only appear as the return value of functions so I don't see where they are defined.

    enum ActionChoices {
        setNumber = "SET_NUMBER",
        incrementNumber = "INCREMENT_NUMBER"
    }

    function setNumber(value: number) : SetAction {
        return {
            type: ActionChoices.setNumber as typeof ActionChoices.setNumber,
            value: value
        }
    }

**Comment by svenwiegand** [comment]
You're right, looks like a copy & paste error: Simply remove the return type declaration, so that TypeScript can infer it. This should work fine. Can you please confirm? Then I can update the documentation afterwards.

**Comment by jmagaram** [comment]
I can’t confirm since I didn’t download and build the code. I’m just trying to understand it by looking at your code and docs. On iPhone now. Truthfully I’m just 1 week in to learning JavaScript and React coming from a C# background so this is all a bit confusing to me. I think it is tough for me to grok without downloading and mousing over since I can’t see the type inference results.

________________________________

**Comment by svenwiegand** [comment]
Okay, understood. I've fixed the `README.md` and thus mark this as fixed. Thanks again for the hint.

For trying around, you can checkout my [https://github.com/svenwiegand/react-typescript-cssmodules-starter](react-typescript-cssmodules-starter) project. It also uses `typed-redux-actions` and specifies a simple state with actions and reducers.
